SELECT 
    (SELECT SUM(S_PRICE) FROM SELL) AS toplam_satis,
    (SELECT SUM(T_PRICE) FROM PURCHASE) AS toplam_alim,
    (SELECT SUM(S_PRICE) FROM SELL) - (SELECT SUM(T_PRICE) FROM PURCHASE) AS fark;
