
SELECT C.CAR_BRAND, C.CAR_MODAL,
       (SELECT COUNT(*) FROM PURCHASE P WHERE P.CAR_ID = C.CAR_ID) AS alim_sayisi,
       (SELECT COUNT(*) FROM SELL S WHERE S.CAR_ID = C.CAR_ID) AS satis_sayisi
FROM CAR C;
